services:
    servicebus.handler:
        class: ServiceBus\ServiceBusHandlerResolver
        public: false

    servicebus.mediator:
        public: true
        class: ServiceBus\Mediator
        arguments: ["@servicebus.handler"]
